"""Generate the AutoInfo documentation inventory (docs-as-code).

Run from the project root:

    python3 scripts/doc_inventory.py          # regenerate docs/dev/doc-inventory.md
    python3 scripts/doc_inventory.py --check  # cross-doc consistency check, exit 0 = clean

Pure Python 3.11 stdlib only (pathlib, re, argparse, subprocess) — no
yaml/pyyaml or any third-party dependency; live counts are read by shelling out
to the interpreter. Scans ``docs/**/*.md``, ``docs/**/*.yaml`` and
``docs/**/*.json`` (JSON-LD schemas in docs/schemas/) and emits
a Markdown report to ``docs/dev/doc-inventory.md`` (the ONLY file this script
writes). The report carries an AUTO-GENERATED header so hand edits are
detectable; never hand-maintain the inventory — regenerate it.

``--check`` (no writes) verifies:
  1. Cross-doc consistency of the seven drift-prone facts extracted from
     README.md and AGENTS.md via regex (MCP tool count, CLI command groups,
     delivery channels, validation scenarios, demo domains, LLM-required
     tools, test count) — README value, AGENTS.md value, match/mismatch are
     all reported.
  2. The same facts extracted from the doc-manager skill
     (``.opencode/skills/doc-manager-skill/SKILL.md``) agree with README.md —
     the skill's own numbers can no longer silently drift.
  3. No stray ``tests/test_bug_*`` files exist in the tests/ root.
  4. ``docs/dev/doc-inventory.md`` matches what ``scan_docs()`` would emit
     right now (byte-for-byte) and carries the AUTO-GENERATED header — so an
     inventory that missed a doc add/edit/remove FAILS the check instead of
     passing on the header alone.
  5. The live declared tool count (``len(_full_tool_list())`` in
     ``src/autoinfo/mcp/server.py``) agrees with README.md, and the
     ``server.py`` module docstring's "N tools across M categories" claim
     agrees with the live tool count and the README-declared category count.
  6. Every declared tool name is enumerated in the README "MCP Tools" table
     (completeness both ways) and the README table's category-row count agrees
     with the README/AGENTS declared category count.
  7. The live pytest collected count agrees with README.md's test count.

Exits non-zero on any failure. Idempotent: regenerating twice produces the
same bytes (no timestamps). ``--check`` shells out to the interpreter for the
live tool list and the pytest collection (the ~30s pytest collect dominates).
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = DOCS / "dev" / "doc-inventory.md"
TESTS = ROOT / "tests"
README = ROOT / "README.md"
AGENTS = ROOT / "AGENTS.md"
SCENARIOS_DIR = ROOT / "src" / "autoinfo" / "mcp" / "scenarios"
#: The MCP server module whose live tool list + docstring counts are checked.
SERVER = ROOT / "src" / "autoinfo" / "mcp" / "server.py"
#: The doc-manager skill whose own drift-prone numbers must agree with README.
SKILL = ROOT / ".opencode" / "skills" / "doc-manager-skill" / "SKILL.md"

#: Exact first line of the generated report; ``--check`` requires it.
HEADER = (
    "<!-- AUTO-GENERATED by scripts/doc_inventory.py — do not edit by hand. "
    "Regenerate: python3 scripts/doc_inventory.py -->"
)

#: Path segments (relative to docs/) that map to a category, in priority order.
#: ``archive`` is handled separately (it also drives the status column).
CATEGORY_SEGMENTS = (
    "specs",
    "skills",
    "schemas",
    "adr",
    "known-limitations",
    "validation-reports",
    "reports",
    "epics",
)
CATEGORY_ORDER = (
    "archive",
    "epics",
    "known-limitations",
    "reports",
    "schemas",
    "skills",
    "adr",
    "specs",
    "validation-reports",
    "docs/dev",
    "docs/root",
)

#: Frontmatter convention: ``<!-- doc-type: market-positioning -->``
DOC_TYPE_RE = re.compile(r"<!--\s*doc-type:\s*([^>]+?)\s*-->")


def read_text(path: Path) -> str:
    """Read a file as UTF-8, tolerating non-UTF-8 bytes in legacy docs."""
    return path.read_text(encoding="utf-8", errors="replace")


def categorize(rel: Path) -> str:
    """Map a docs-relative path to its category by path segment."""
    parts = rel.parts
    if "archive" in parts:
        return "archive"
    for seg in CATEGORY_SEGMENTS:
        if seg in parts:
            return seg
    return "docs/root" if len(parts) == 1 else "docs/dev"


def status_of(rel: Path) -> str:
    """'archived' for paths under docs/archive/, else 'active'."""
    return "archived" if "archive" in rel.parts else "active"


def scan_docs() -> list[dict[str, Any]]:
    """Return one row per docs/**/*.md, *.yaml or *.json file (sorted, stable)."""
    paths: set[Path] = set()
    for suffix in ("*.md", "*.yaml", "*.json"):
        paths.update(DOCS.rglob(suffix))
    rows: list[dict[str, Any]] = []
    for path in sorted(paths, key=lambda p: p.relative_to(DOCS).as_posix()):
        if path == OUT:
            continue  # never list the inventory itself (breaks idempotency)
        rel = path.relative_to(DOCS)
        text = read_text(path)
        m = DOC_TYPE_RE.search(text)
        rows.append(
            {
                "path": rel.as_posix(),
                "lines": len(text.splitlines()),
                "category": categorize(rel),
                "status": status_of(rel),
                "doc_type": m.group(1).strip() if m else "\u2014",
            }
        )
    return rows


def esc(value: str) -> str:
    """Escape a value for a Markdown table cell."""
    return value.replace("|", "\\|")


def render_report(rows: list[dict[str, Any]]) -> str:
    """Build the full Markdown report (header + summary + inventory)."""
    total_lines = sum(r["lines"] for r in rows)
    active = sum(1 for r in rows if r["status"] == "active")
    archived = sum(1 for r in rows if r["status"] == "archived")

    lines: list[str] = [HEADER, "", "# Documentation Inventory", ""]
    lines.append(
        "AUTO-GENERATED inventory of Markdown/YAML/JSON files under `docs/`, "
        "produced by `scripts/doc_inventory.py`. **Do not edit by hand.** "
        "Regenerate:"
    )
    lines.append("")
    lines.append("```bash")
    lines.append("python3 scripts/doc_inventory.py          # regenerate this file")
    lines.append(
        "python3 scripts/doc_inventory.py --check  # cross-doc consistency (exit 0 = clean)"
    )
    lines.append("```")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total files | {len(rows)} |")
    lines.append(f"| Total lines | {total_lines} |")
    lines.append(f"| Active files | {active} |")
    lines.append(f"| Archived files | {archived} |")
    for cat in CATEGORY_ORDER:
        cat_rows = [r for r in rows if r["category"] == cat]
        if not cat_rows:
            continue
        cat_lines = sum(r["lines"] for r in cat_rows)
        lines.append(f"| Category \u2014 {cat} | {len(cat_rows)} files / {cat_lines} lines |")
    lines.append("")
    lines.append("## Inventory")
    lines.append("")
    lines.append("| Relative path | Lines | Category | Status | Doc-type |")
    lines.append("|---------------|------:|----------|--------|----------|")
    for r in rows:
        lines.append(
            f"| `{esc(r['path'])}` | {r['lines']} | {esc(r['category'])} "
            f"| {esc(r['status'])} | {esc(r['doc_type'])} |"
        )
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# --check: cross-doc consistency facts (README.md vs AGENTS.md vs SKILL.md)
# ---------------------------------------------------------------------------

#: (fact name, regex) — first match wins; pattern must hit BOTH README and AGENTS.
FACTS: list[tuple[str, str]] = [
    ("MCP tool count", r"(\d+)\s+tools\s+across"),
    ("MCP categories", r"(\d+)\s+categories?"),
    ("CLI command groups", r"(\d+)\s+command groups?"),
    ("Delivery channels", r"(\d+)\s+(?:delivery\s+)?channels?"),
    ("Validation scenarios", r"(\d+)\s+scenarios?"),
    ("Demo domains", r"(\d+)\s+demo domains?"),
    ("LLM-required tools", r"(\d+)\s+LLM-required tools"),
    ("Test count", r"~(\d+)\s+tests?"),
]

#: (fact name, regex) tuned to the doc-manager skill's own phrasing (§3 Step 3);
#: checked against the README value so the skill's numbers cannot drift silently.
SKILL_FACTS: list[tuple[str, str]] = [
    ("MCP tool count", r"MCP tools?\s+(\d+)"),
    ("CLI command groups", r"CLI groups\s+(\d+)"),
    ("Delivery channels", r"delivery channels\s+(\d+)"),
    ("Validation scenarios", r"validation scenarios\s+(\d+)"),
    ("Demo domains", r"demo domains\s+(\d+)"),
    ("LLM-required tools", r"LLM-required tools\s+(\d+)"),
    ("Test count", r"test count\s+~?(\d+)"),
]


def extract_number(text: str, pattern: str) -> str | None:
    m = re.search(pattern, text)
    return m.group(1) if m else None


def _run(args: list[str], timeout: int) -> tuple[int, str, str] | None:
    """Run a subprocess; ``None`` if it could not be launched (timeout/OSError)."""
    try:
        proc = subprocess.run(args, cwd=ROOT, capture_output=True, text=True, timeout=timeout)
    except (OSError, subprocess.SubprocessError):
        return None
    return proc.returncode, proc.stdout, proc.stderr


def live_tool_names() -> tuple[list[str] | None, str | None]:
    """Return the live declared tool names from ``_full_tool_list()``.

    Shells out to the interpreter so this script's own imports stay stdlib-only.
    Returns ``(names, None)`` on success, ``(None, error)`` otherwise — never a
    silent empty success (that is the ``misleading_success_output`` failure mode).
    """
    code = (
        "import sys; sys.path.insert(0, 'src'); "
        "from autoinfo.mcp.server import _full_tool_list as f; "
        "[print(t.name) for t in f()]"
    )
    result = _run([sys.executable, "-c", code], timeout=120)
    if result is None:
        return None, "subprocess failed to launch (timeout or OSError)"
    rc, out, err = result
    if rc != 0:
        lines = [ln for ln in err.strip().splitlines() if ln.strip()]
        return None, lines[-1] if lines else "unknown import error"
    names = [ln.strip() for ln in out.splitlines() if ln.strip()]
    if not names:
        return None, "empty output from _full_tool_list()"
    return names, None


def pytest_collected_count() -> tuple[int | None, str | None]:
    """Return the live pytest collected count, or ``(None, error)``."""
    result = _run(
        [
            sys.executable,
            "-m",
            "pytest",
            "--collect-only",
            "-q",
            "-p",
            "no:cacheprovider",
        ],
        timeout=600,
    )
    if result is None:
        return None, "pytest subprocess failed to launch (timeout or OSError)"
    rc, out, err = result
    m = re.search(r"(\d+)\s+tests?\s+collected", f"{out}\n{err}")
    if m is None:
        return None, f"unparsable pytest output (exit {rc})"
    return int(m.group(1)), None


#: README "MCP Tools (N)" section up to the next H2, whose rows are
#: ``| **Category** | tool_a, tool_b, ... |``.
_README_MCP_SECTION_RE = re.compile(r"##\s+MCP Tools\s+\((\d+)\)(.*?)##\s+Demo Domains", re.S)
_README_MCP_ROW_RE = re.compile(r"^\|\s*\*\*(.+?)\*\*\s*\|(.*?)\|\s*$", re.M)
_TOOL_NAME_RE = re.compile(r"[a-z_][a-z0-9_]*")


def _split_top_level(value: str) -> list[str]:
    """Split a Markdown cell on commas not nested inside (), [], or {}."""
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for ch in value:
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth = max(0, depth - 1)
        if ch == "," and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(ch)
    parts.append("".join(current))
    return parts


def readme_tool_table(
    readme_text: str,
) -> tuple[int, list[str], list[str]] | None:
    """Parse the README MCP table → (header count, category names, tool names)."""
    section = _README_MCP_SECTION_RE.search(readme_text)
    if section is None:
        return None
    rows = _README_MCP_ROW_RE.findall(section.group(2))
    categories = [name.strip() for name, _ in rows]
    tools: list[str] = []
    for _, cell in rows:
        for raw in _split_top_level(cell):
            name = re.sub(r"\(.*$", "", raw.strip()).strip("*` ").strip()
            if _TOOL_NAME_RE.fullmatch(name):
                tools.append(name)
    return int(section.group(1)), categories, tools


def _server_docstring_counts(server_text: str) -> tuple[int, int] | None:
    """Extract ``(tool_count, category_count)`` from the module docstring claim."""
    doc = re.match(r'\s*"""(.*?)"""', server_text, re.S)
    scope = doc.group(1) if doc else server_text[:4000]
    m = re.search(r"(\d+)\s+tools?\s+across\s+(\d+)\s+categor(?:y|ies)", scope)
    if m is None:
        return None
    return int(m.group(1)), int(m.group(2))


def run_check() -> list[str]:
    """Check cross-doc consistency; return the list of human-readable failures."""
    failures: list[str] = []
    readme_text = read_text(README)
    agents_text = read_text(AGENTS)

    readme_values: dict[str, str | None] = {}
    for fact, pattern in FACTS:
        rv = extract_number(readme_text, pattern)
        av = extract_number(agents_text, pattern)
        match = rv is not None and rv == av
        rv_disp = rv if rv is not None else "not found"
        av_disp = av if av is not None else "not found"
        print(
            f"  {fact}: README.md={rv_disp}, AGENTS.md={av_disp} "
            f"-> {'match' if match else 'MISMATCH'}"
        )
        readme_values[fact] = rv
        if not match:
            failures.append(f"fact '{fact}': README.md={rv_disp} vs AGENTS.md={av_disp}")

    skill_text = read_text(SKILL) if SKILL.exists() else ""
    for fact, pattern in SKILL_FACTS:
        rv = readme_values.get(fact)
        sv = extract_number(skill_text, pattern) if skill_text else None
        match = rv is not None and sv == rv
        rv_disp = rv if rv is not None else "not found"
        sv_disp = sv if sv is not None else "not found"
        print(
            f"  SKILL.md {fact}: README.md={rv_disp}, SKILL.md={sv_disp} "
            f"-> {'match' if match else 'MISMATCH'}"
        )
        if not match:
            failures.append(
                f"doc-manager-skill '{fact}': SKILL.md={sv_disp} vs README.md={rv_disp} — "
                f"update .opencode/skills/doc-manager-skill/SKILL.md (§3 Step 3)"
            )

    # On-disk scenario count validation (issue #215): the README/AGENTS/SKILL
    # cross-checks above can all agree on a stale number; assert against the
    # actual .yaml files under src/autoinfo/mcp/scenarios/.
    claimed_readme = readme_values.get("Validation scenarios")
    if claimed_readme is not None:
        actual = sum(1 for _ in SCENARIOS_DIR.rglob("*.yaml"))
        status = "match" if actual == int(claimed_readme) else "MISMATCH"
        print(
            f"  Validation scenarios on disk: {actual} yaml files "
            f"vs README.md={claimed_readme} -> {status}"
        )
        if actual != int(claimed_readme):
            failures.append(
                f"validation scenario count drift: README.md={claimed_readme} vs actual "
                f"{actual} .yaml files under {SCENARIOS_DIR.relative_to(ROOT)}"
            )

    live_names, live_err = live_tool_names()
    live_count = len(live_names) if live_names is not None else None
    readme_tool_fact = readme_values.get("MCP tool count")
    readme_cat_fact = readme_values.get("MCP categories")
    if live_names is None:
        print(f"  Live MCP tools (_full_tool_list): unavailable -> {live_err}")
        failures.append(
            f"could not read live tool list from {SERVER.relative_to(ROOT)}: {live_err}"
        )
    else:
        print(f"  Live MCP tools (_full_tool_list): {live_count}")

    table = readme_tool_table(readme_text)
    if table is None:
        print("  README MCP Tools table: not found -> FAIL")
        failures.append("README.md has no parseable '## MCP Tools (N)' table")
    else:
        header_count, categories, table_names = table
        unique_table = set(table_names)
        if live_names is not None:
            declared_set = set(live_names)
            missing = sorted(declared_set - unique_table)
            extra = sorted(unique_table - declared_set)
            if missing or extra:
                details = []
                if missing:
                    details.append(
                        f"{len(missing)} declared tool(s) not enumerated: {', '.join(missing)}"
                    )
                if extra:
                    details.append(
                        f"{len(extra)} enumerated name(s) not declared: {', '.join(extra)}"
                    )
                print(f"  README MCP table completeness: MISMATCH — {'; '.join(details)}")
                failures.append(f"README 'MCP Tools' table completeness: {'; '.join(details)}")
            else:
                print(
                    f"  README MCP table completeness: all {len(declared_set)} declared tools "
                    f"enumerated ({len(table_names)} entries) -> match"
                )
        if live_count is not None and header_count != live_count:
            print(f"  README MCP Tools header: {header_count} vs live {live_count} -> MISMATCH")
            failures.append(
                f"README '## MCP Tools (N)' header={header_count} vs live "
                f"_full_tool_list()={live_count}"
            )
        if readme_cat_fact is not None and len(categories) != int(readme_cat_fact):
            print(
                f"  README MCP category rows: {len(categories)} vs declared "
                f"{readme_cat_fact} -> MISMATCH"
            )
            failures.append(
                f"README MCP table has {len(categories)} category rows vs declared "
                f"{readme_cat_fact} categories"
            )
        else:
            print(
                f"  README MCP category rows: {len(categories)} vs declared "
                f"{readme_cat_fact if readme_cat_fact is not None else 'not found'} -> "
                f"{'match' if readme_cat_fact is not None else 'n/a'}"
            )

    if (
        live_count is not None
        and readme_tool_fact is not None
        and int(readme_tool_fact) != live_count
    ):
        print(f"  README declared MCP tools: {readme_tool_fact} vs live {live_count} -> MISMATCH")
        failures.append(
            f"README.md MCP tool count={readme_tool_fact} vs live _full_tool_list()={live_count}"
        )

    server_text = read_text(SERVER) if SERVER.exists() else ""
    doc_counts = _server_docstring_counts(server_text) if server_text else None
    if doc_counts is None:
        print("  server.py docstring 'N tools across M categories': not found -> FAIL")
        failures.append(
            f"{SERVER.relative_to(ROOT)} module docstring does not state "
            "'N tools across M categories'"
        )
    else:
        doc_tools, doc_cats = doc_counts
        problems = []
        if live_count is not None and doc_tools != live_count:
            problems.append(f"tools {doc_tools} != live {live_count}")
        if readme_cat_fact is not None and doc_cats != int(readme_cat_fact):
            problems.append(f"categories {doc_cats} != README {readme_cat_fact}")
        if problems:
            print(f"  server.py docstring counts: MISMATCH — {'; '.join(problems)}")
            failures.append(f"{SERVER.relative_to(ROOT)} docstring counts: {'; '.join(problems)}")
        else:
            print(
                f"  server.py docstring counts: {doc_tools} tools / {doc_cats} categories -> match"
            )

    readme_test_fact = readme_values.get("Test count")
    collected, collected_err = pytest_collected_count()
    if collected is None:
        print(f"  Pytest collected: unavailable -> {collected_err}")
        failures.append(f"could not read pytest collected count: {collected_err}")
    elif readme_test_fact is None:
        print(f"  Pytest collected: {collected} vs README.md=not found -> MISMATCH")
        failures.append(f"pytest collected={collected} but README.md test count was not found")
    else:
        status = "match" if collected == int(readme_test_fact) else "MISMATCH"
        print(f"  Pytest collected: {collected} vs README.md={readme_test_fact} -> {status}")
        if collected != int(readme_test_fact):
            failures.append(
                f"pytest collected count drift: README.md={readme_test_fact} vs actual {collected}"
            )

    stray = sorted(TESTS.glob("test_bug_*")) if TESTS.is_dir() else []
    if stray:
        names = ", ".join(p.name for p in stray)
        print(f"  Stray regression files: {names} -> FAIL")
        failures.append(f"tests/ contains {len(stray)} test_bug_* file(s): {names}")
    else:
        print("  Stray test_bug_* files in tests/: none -> ok")

    if not OUT.exists():
        print("  docs/dev/doc-inventory.md: does not exist -> FAIL")
        failures.append(
            "docs/dev/doc-inventory.md missing — run python3 scripts/doc_inventory.py first"
        )
    else:
        actual = read_text(OUT)
        rows = scan_docs()
        expected = render_report(rows)
        first = actual.splitlines()[0] if actual.splitlines() else ""
        header_ok = first.startswith("<!-- AUTO-GENERATED by scripts/doc_inventory.py")
        if not header_ok:
            print("  docs/dev/doc-inventory.md: AUTO-GENERATED header MISSING -> FAIL")
            failures.append(
                "docs/dev/doc-inventory.md is stale: missing its AUTO-GENERATED header "
                "— regenerate with python3 scripts/doc_inventory.py"
            )
        elif actual != expected:
            print("  docs/dev/doc-inventory.md: content differs from a fresh scan -> FAIL")
            failures.append(
                "docs/dev/doc-inventory.md is stale: not byte-identical to a fresh "
                "`scripts/doc_inventory.py` run (a doc was added, edited or removed "
                "without regenerating) — regenerate with "
                "python3 scripts/doc_inventory.py"
            )
        else:
            print(
                f"  docs/dev/doc-inventory.md: header present, content fresh "
                f"({len(rows)} files) -> ok"
            )

    return failures


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the AutoInfo documentation inventory (docs/dev/doc-inventory.md)."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify cross-doc consistency (README vs AGENTS facts, stray test_bug_* files, "
        "stale inventory). No files are written. Exits 1 on any failure.",
    )
    args = parser.parse_args(argv)

    if args.check:
        print("doc_inventory --check")
        failures = run_check()
        print()
        if failures:
            print(f"check FAILED ({len(failures)} issue(s)):")
            for f in failures:
                print(f"  - {f}")
            return 1
        print("check passed: all facts match, no stray files, inventory fresh.")
        return 0

    rows = scan_docs()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render_report(rows), encoding="utf-8")
    total_lines = sum(r["lines"] for r in rows)
    print(f"Wrote {OUT} ({len(rows)} files, {total_lines} lines).")
    print("Regenerate after doc changes; verify with --check (exit 0 = clean).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
