"""Generate the AutoInfo documentation inventory (docs-as-code).

Run from the project root:

    python3 scripts/doc_inventory.py          # regenerate docs/dev/doc-inventory.md
    python3 scripts/doc_inventory.py --check  # cross-doc consistency check, exit 0 = clean

Pure Python 3.11 stdlib only (pathlib, re, argparse) — no yaml/pyyaml or any
third-party dependency. Scans ``docs/**/*.md`` and ``docs/**/*.yaml`` and emits
a Markdown report to ``docs/dev/doc-inventory.md`` (the ONLY file this script
writes). The report carries an AUTO-GENERATED header so hand edits are
detectable; never hand-maintain the inventory — regenerate it.

``--check`` (no writes) verifies:
  1. Cross-doc consistency of the five drift-prone facts extracted from
     README.md and AGENTS.md via regex (MCP tool count, CLI command groups,
     delivery channels, validation scenarios, demo domains) — README value,
     AGENTS.md value, match/mismatch are all reported.
  2. No stray ``tests/test_bug_*`` files exist in the tests/ root.
  3. ``docs/dev/doc-inventory.md`` exists and carries its AUTO-GENERATED
     header (stale-inventory detection).

Exits non-zero on any failure. Idempotent: regenerating twice produces the
same bytes (no timestamps); fast (<2s, ~40 files, no network).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = DOCS / "dev" / "doc-inventory.md"
TESTS = ROOT / "tests"
README = ROOT / "README.md"
AGENTS = ROOT / "AGENTS.md"

#: Exact first line of the generated report; ``--check`` requires it.
HEADER = (
    "<!-- AUTO-GENERATED by scripts/doc_inventory.py — do not edit by hand. "
    "Regenerate: python3 scripts/doc_inventory.py -->"
)

#: Path segments (relative to docs/) that map to a category, in priority order.
#: ``archive`` is handled separately (it also drives the status column).
CATEGORY_SEGMENTS = (
    "specs",
    "skills",
    "known-limitations",
    "validation-reports",
    "reports",
    "epics",
)
CATEGORY_ORDER = (
    "archive",
    "epics",
    "known-limitations",
    "reports",
    "skills",
    "specs",
    "validation-reports",
    "docs/dev",
    "docs/root",
)

#: Frontmatter convention: ``<!-- doc-type: market-positioning -->``
DOC_TYPE_RE = re.compile(r"<!--\s*doc-type:\s*([^>]+?)\s*-->")


def read_text(path: Path) -> str:
    """Read a file as UTF-8, tolerating non-UTF-8 bytes in legacy docs."""
    return path.read_text(encoding="utf-8", errors="replace")


def categorize(rel: Path) -> str:
    """Map a docs-relative path to its category by path segment."""
    parts = rel.parts
    if "archive" in parts:
        return "archive"
    for seg in CATEGORY_SEGMENTS:
        if seg in parts:
            return seg
    return "docs/root" if len(parts) == 1 else "docs/dev"


def status_of(rel: Path) -> str:
    """'archived' for paths under docs/archive/, else 'active'."""
    return "archived" if "archive" in rel.parts else "active"


def scan_docs() -> list[dict[str, Any]]:
    """Return one row per docs/**/*.md or *.yaml file (sorted, stable)."""
    paths: set[Path] = set()
    for suffix in ("*.md", "*.yaml"):
        paths.update(DOCS.rglob(suffix))
    rows: list[dict[str, Any]] = []
    for path in sorted(paths, key=lambda p: p.relative_to(DOCS).as_posix()):
        if path == OUT:
            continue  # never list the inventory itself (breaks idempotency)
        rel = path.relative_to(DOCS)
        text = read_text(path)
        m = DOC_TYPE_RE.search(text)
        rows.append(
            {
                "path": rel.as_posix(),
                "lines": len(text.splitlines()),
                "category": categorize(rel),
                "status": status_of(rel),
                "doc_type": m.group(1).strip() if m else "\u2014",
            }
        )
    return rows


def esc(value: str) -> str:
    """Escape a value for a Markdown table cell."""
    return value.replace("|", "\\|")


def render_report(rows: list[dict[str, Any]]) -> str:
    """Build the full Markdown report (header + summary + inventory)."""
    total_lines = sum(r["lines"] for r in rows)
    active = sum(1 for r in rows if r["status"] == "active")
    archived = sum(1 for r in rows if r["status"] == "archived")

    lines: list[str] = [HEADER, "", "# Documentation Inventory", ""]
    lines.append(
        "AUTO-GENERATED inventory of Markdown/YAML files under `docs/`, produced by "
        "`scripts/doc_inventory.py`. **Do not edit by hand.** Regenerate:"
    )
    lines.append("")
    lines.append("```bash")
    lines.append("python3 scripts/doc_inventory.py          # regenerate this file")
    lines.append("python3 scripts/doc_inventory.py --check  # cross-doc consistency (exit 0 = clean)")
    lines.append("```")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total files | {len(rows)} |")
    lines.append(f"| Total lines | {total_lines} |")
    lines.append(f"| Active files | {active} |")
    lines.append(f"| Archived files | {archived} |")
    for cat in CATEGORY_ORDER:
        cat_rows = [r for r in rows if r["category"] == cat]
        if not cat_rows:
            continue
        cat_lines = sum(r["lines"] for r in cat_rows)
        lines.append(f"| Category \u2014 {cat} | {len(cat_rows)} files / {cat_lines} lines |")
    lines.append("")
    lines.append("## Inventory")
    lines.append("")
    lines.append("| Relative path | Lines | Category | Status | Doc-type |")
    lines.append("|---------------|------:|----------|--------|----------|")
    for r in rows:
        lines.append(
            f"| `{esc(r['path'])}` | {r['lines']} | {esc(r['category'])} "
            f"| {esc(r['status'])} | {esc(r['doc_type'])} |"
        )
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# --check: cross-doc consistency facts (README.md vs AGENTS.md)
# ---------------------------------------------------------------------------

#: (fact name, regex) — first match wins; pattern must hit BOTH docs.
FACTS: list[tuple[str, str]] = [
    ("MCP tool count", r"(\d+)\s+tools\s+across"),
    ("CLI command groups", r"(\d+)\s+command groups?"),
    ("Delivery channels", r"(\d+)\s+(?:delivery\s+)?channels?"),
    ("Validation scenarios", r"(\d+)\s+scenarios?"),
    ("Demo domains", r"(\d+)\s+demo domains?"),
]


def extract_number(text: str, pattern: str) -> str | None:
    m = re.search(pattern, text)
    return m.group(1) if m else None


def run_check() -> list[str]:
    """Check cross-doc consistency; return the list of human-readable failures."""
    failures: list[str] = []
    readme_text = read_text(README)
    agents_text = read_text(AGENTS)

    for fact, pattern in FACTS:
        rv = extract_number(readme_text, pattern)
        av = extract_number(agents_text, pattern)
        match = rv is not None and rv == av
        rv_disp = rv if rv is not None else "not found"
        av_disp = av if av is not None else "not found"
        print(f"  {fact}: README.md={rv_disp}, AGENTS.md={av_disp} "
              f"-> {'match' if match else 'MISMATCH'}")
        if not match:
            failures.append(f"fact '{fact}': README.md={rv_disp} vs AGENTS.md={av_disp}")

    stray = sorted(TESTS.glob("test_bug_*")) if TESTS.is_dir() else []
    if stray:
        names = ", ".join(p.name for p in stray)
        print(f"  Stray regression files: {names} -> FAIL")
        failures.append(f"tests/ contains {len(stray)} test_bug_* file(s): {names}")
    else:
        print("  Stray test_bug_* files in tests/: none -> ok")

    if OUT.exists():
        first = read_text(OUT).splitlines()[0] if read_text(OUT).splitlines() else ""
        header_ok = first.startswith("<!-- AUTO-GENERATED by scripts/doc_inventory.py")
        if header_ok:
            print("  docs/dev/doc-inventory.md: AUTO-GENERATED header present -> ok")
        else:
            print("  docs/dev/doc-inventory.md: AUTO-GENERATED header MISSING -> FAIL")
            failures.append("docs/dev/doc-inventory.md is stale: missing its AUTO-GENERATED header — regenerate with python3 scripts/doc_inventory.py")
    else:
        print("  docs/dev/doc-inventory.md: does not exist -> FAIL")
        failures.append("docs/dev/doc-inventory.md missing — run python3 scripts/doc_inventory.py first")

    return failures


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the AutoInfo documentation inventory (docs/dev/doc-inventory.md)."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify cross-doc consistency (README vs AGENTS facts, stray test_bug_* files, "
        "stale inventory header). No files are written. Exits 1 on any failure.",
    )
    args = parser.parse_args(argv)

    if args.check:
        print("doc_inventory --check")
        failures = run_check()
        print()
        if failures:
            print(f"check FAILED ({len(failures)} issue(s)):")
            for f in failures:
                print(f"  - {f}")
            return 1
        print("check passed: all facts match, no stray files, inventory fresh.")
        return 0

    rows = scan_docs()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render_report(rows), encoding="utf-8")
    total_lines = sum(r["lines"] for r in rows)
    print(f"Wrote {OUT} ({len(rows)} files, {total_lines} lines).")
    print(f"Regenerate after doc changes; verify with --check (exit 0 = clean).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
