#!/usr/bin/env python3
"""Generate a versioned validation run report (fixes #129 P0-2).

Reads the persisted scenario results from ``validation-runs/<run>/scenarios.json``
(the newest run by default) and emits an executive report to
``docs/dev/validation-reports/launch-validation-<version>-<runid>.md``.

The report uses the framework ``§6`` executive-summary skeleton: verdict counts,
scenario status table, artifact manifest, and an appendix pointer back to the
framework template and evidence catalog.

Usage:
    python3 scripts/validation_report.py [--version VERSION] [--run RUN_ID]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
RUNS = ROOT / "validation-runs"
REPORTS = ROOT / "docs" / "dev" / "validation-reports"
FRAMEWORK = "docs/dev/launch-validation-framework.md"
TEMPLATE = "docs/dev/launch-validation-template.md"


def _latest_run() -> str:
    pointer = RUNS / "latest.txt"
    if pointer.exists():
        return pointer.read_text().strip()
    raise SystemExit(f"No validation runs found under {RUNS}; run scenarios with save_results first.")


def _status_counts(scenarios: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for sc in scenarios:
        status = sc.get("status", "unknown")
        counts[status] = counts.get(status, 0) + 1
    return counts


def generate(version: str, run_id: str) -> Path:
    run_dir = RUNS / run_id
    payload_path = run_dir / "scenarios.json"
    if not payload_path.exists():
        raise SystemExit(f"scenarios.json not found in {run_dir}")
    payload = json.loads(payload_path.read_text(encoding="utf-8"))
    scenarios: list[dict[str, Any]] = payload.get("scenarios", [])
    counts = _status_counts(scenarios)
    passed = counts.get("passed", 0)
    failed = counts.get("failed", 0)
    unconfigured = counts.get("unconfigured", 0)

    REPORTS.mkdir(parents=True, exist_ok=True)
    out = REPORTS / f"launch-validation-{version}-{run_id}.md"

    lines: list[str] = []
    lines.append(f"# Launch Validation Run Report {version} ({run_id})")
    lines.append("")
    lines.append(f"> Run: {run_id} | Scenarios: {len(scenarios)} "
                 f"(passed={passed}, failed={failed}, unconfigured={unconfigured})")
    lines.append(">")
    lines.append(f"> Template: `{FRAMEWORK}` | Skeleton: `§6` | Evidence catalog: appendix of the template")
    lines.append("")
    lines.append("## Verdicts")
    lines.append("")
    lines.append("| Scenario | Status | Passed/Total |")
    lines.append("|----------|--------|---|")
    for sc in sorted(scenarios, key=lambda x: x.get("scenario", "")):
        summary = sc.get("summary", {})
        lines.append(f"| {sc.get('scenario', '?')} | {sc.get('status', '?')} "
                     f"| {summary.get('passed', 0)}/{summary.get('total', 0)} |")
    lines.append("")
    lines.append("## Executive summary")
    lines.append("")
    if failed or unconfigured:
        lines.append(f"{failed} scenario(s) failed and {unconfigured} were unconfigured; "
                     f"{passed} passed. See the per-scenario status table and the evidence "
                     f"files under `{run_dir}` for details.")
    else:
        lines.append(f"All {passed} scenario(s) passed. Evidence available under `{run_dir}`.")
    lines.append("")
    lines.append("## Blockers")
    lines.append("")
    lines.append("Findings only; B3 (director) disposes. See the `§6` blocker format in the "
                 "framework template.")
    lines.append("")
    lines.append("## Appendix pointer")
    lines.append("")
    ev = run_dir / "evidence"
    if ev.is_dir():
        for f in sorted(ev.rglob("*")):
            if f.is_file():
                lines.append(f"- `{f.relative_to(ROOT)}`")
    else:
        lines.append(f"(no evidence subdir yet — artifacts appear under `{run_dir}` on collect)")
    lines.append("")
    lines.append("Generated by `python3 scripts/validation_report.py`.")
    lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a versioned validation run report")
    parser.add_argument("--version", default="unreleased", help="Release/feature version label")
    parser.add_argument("--run", default="", help="Run ID (default: newest from latest.txt)")
    args = parser.parse_args()

    run_id = args.run or _latest_run()
    import os
    version = args.version or os.environ.get("AUTOINFO_VERSION", "unreleased")
    out = generate(version, run_id)
    print(f"REPORT: {out}")


if __name__ == "__main__":
    sys.exit(main())
